---
title: "Figure_3F"
author: "Mike O'Donnell"
date: "6/10/2019"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r 30pct data}
library(tidyverse)
library(emmeans)
library(modelr)
library(tidybayes)
library(kableExtra)
library(patchwork)
theme_set(theme_my)


SOS_30pct2KO <- SOS %>% dplyr::filter(genotype == "tdc-1", 
                                      cond == "20min_off_food", 
                                      response.time < 20, 
                                      date %in% c("2019_05_20", "2019_06_07")) %>%
  mutate(food = fct_relevel(food, c("OP50", "JUb39")),
         data_type = "raw") %>% droplevels()


# 
# SOS_30pct2KO %>% ggplot(aes(x = genotype, y = response.time)) +
#   #geom_boxplot(outlier.shape =NA) +
#   #geom_point(pch = 21) +#, position = position_jitterdodge()) +
#   ggbeeswarm::geom_quasirandom(aes(colour = food), width = 0.2) +
#   scale_color_plot("grey-blue", drop = TRUE) +
#   facet_grid(.~food) +
#   add.mean('response.time', colour = "red") +
#   add.quartiles('response.time') +
#   theme_my +
#   labs(x = "food",
#        y = "time to reversal (s)")

stan_mod <- rstanarm::stan_glmer(data = SOS_30pct2KO, log(response.time) ~ food + (1|date) + (1|plateID),
                       family = gaussian,
                       seed = 694,
                       chains = 6,
                       cores = 6)

mod.data <- emmeans(stan_mod, ~ food) %>%
  coda::as.mcmc() %>% 
  bayesplot::mcmc_intervals_data(transformations = "exp", prob = 0.66, prob_outer = 0.95) %>%
  mutate(food = c("OP50", "JUb39","JUb39; tdcDel::cmR delAADC"))

fitted <- mod.data[[2]] %>%
  data.frame() %>%
  mutate_all(exp)
  rownames_to_column() %>%
  mutate(genotype = rep(c("N2", "tdc-1"), 2),
         food = rep(c("OP50", "JUb39"), each = 2)) %>%
  mutate(interval_type = "HDI",
             data_type = "fit") %>%
      dplyr::select(1:10) %>%
      rename(lower.2.5 = 2,
             lower.17 = 3,
             median = 4,
             upper.83 = 5,
             upper.97.5 = 6)
  

  

fitted <- SOS_30pct2KO %>%
  data_grid(food) %>%
  add_fitted_draws(stan_mod, re_formula = NA) %>%
  mutate(response.time = exp(.value), data_type = "fit")


```

```{r frequentist stats}
sjstats::equi_test(stan_mod)

# frequentist glmm (log transformed)
#singular fit so cannot do full model
lmer <- lme4::lmer(data = SOS_30pct2KO, log(response.time) ~ food  + (1|plateID))

lmer %>% emmeans(pairwise ~ food)


#plot
plot <- SOS_30pct2KO %>%
  mutate(response.time = case_when(
    response.time < 1 ~ 1, 
    TRUE ~ response.time
  ),
  food = fct_relevel(food, "OP50")) %>%
  ggplot(aes(x = data_type, y = response.time)) +
  stat_summary(geom = "bar", fun.y = mean, aes(fill = food), width = 0.75, alpha = 0.5) +
  ggbeeswarm::geom_quasirandom(aes(colour = food), width = 0.2, alpha = 0.75) +
  scale_color_plot("grey-blue", drop = TRUE) +
  scale_fill_plot("grey-blue", drop = TRUE) +
  facet_grid(.~genotype + food, 
             labeller = labeller(genotype = label_wrap_gen(10), 
                                 food = as_labeller(c("OP50" = "",
                                                    "JUb39" = "")))) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
  add.n('data_type', y.pos = 0.9) +
  stat_pointinterval(aes(y=response.time, x = 1.5),
                     data = fitted, fatten_point = 0,
                     size_range = c(0.3, 1), colour = "grey") +
  stat_summary(data = fitted,
               aes(y=response.time, x = 1.5),
               fun.y = median,
               fun.ymin = median,
               fun.ymax = median,
               geom = "crossbar",
               width = 0.05,
               lwd = 0.35,
               colour = "grey") +
  labs(x = "genotype",
       y = "time to reversal (s)") +
  guides(colour = FALSE) +
  theme(axis.text.x = element_blank()) +
  scale_y_log10()

gt <- ggplot_gtable(ggplot_build(plot))
gt$widths[c(8,12,16,20)] = 2*gt$widths[c(8,12,16,20)]
gt$widths[c(6,10,14,18,18)] = .3*gt$widths[c(6,10,14,16,18)]
grid::grid.draw(gt)

# F-test for interaction term using loci as predictors:
lmer2 <- amine_data %>%
  lme4::lmer(data = ., log(response.time) ~ food * tdc * tbh + (1|date) + (1|plateID))
car::Anova(lmer2, test = "F")


# comaprison of mcmc intervals for supplement:
mcmc.comps <- emmeans(stan_mod, ~ food | genotype, type = "response") %>%
  contrast(method = "pairwise") %>%
  coda::as.mcmc() #%>%
p1 <- bayesplot::mcmc_areas(mcmc.comps)
p2 <- bayesplot::mcmc_intervals(mcmc.comps,prob = 0.66, prob_outer = 0.95)

p1 + p2 + theme(axis.text.y = element_blank())
```
