---
title: "Fig_ext3c"
author: "Mike O'Donnell"
date: "5/30/2019"
output: 
  html_document:
      code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
library(scales)
```

```{r}
library(tidyverse)
library(scales)
metabolites <- read_csv('extdata/SI_Table3.csv')

library(magrittr)
metabolites %<>% 
  pivot_longer(cols = 8:25, names_to = "sample", values_to = "AUC") %>%
  separate(sample, into = c("genotype", "bacteria", "replicate"), sep = "_") %>%
  mutate(bacteria = fct_relevel(bacteria, "OP50", "JUb39"),
         AUC = case_when(
           AUC == 0 ~ 1,
           TRUE ~ AUC)) %>%
  droplevels()

Order <- metabolites %>% 
  filter(bacteria == "OP50",
         genotype == "N2",
         !is.na(Formula),
         Formula != "C14H16N2O4") %>% # leave out 5-HT
  group_by(Formula) %>%
  summarize(mean = mean(AUC)) %>%
  arrange(mean)
  
rel_metabolites <- full_join(metabolites, Order) %>%
  mutate(rel_AUC = AUC/mean)

order_rel <- rel_metabolites %>% 
  filter(bacteria == "JUb39",
         genotype == "N2",
         !is.na(Formula),
         Formula != "C14H16N2O4") %>% # leave out 5-HT
  group_by(Formula) %>%
  summarize(mean = mean(rel_AUC)) %>%
  arrange(mean)

plot_rel <- rel_metabolites %>%
  filter(!is.na(Formula),
         Formula != "C14H16N2O4") %>%
  mutate(Formula = fct_relevel(Formula, order_rel$Formula)) %>%
  group_by(bacteria, Formula, genotype) %>%
  summarise(rel_AUC = mean(rel_AUC)) %>%
  ggplot(aes(x = bacteria, y = Formula)) +
  geom_tile(aes(fill = rel_AUC)) +
  facet_grid(.~genotype) +
  scale_fill_viridis_c(oob = squish, limits = c(.01,100), trans = "log10", option = "inferno") +
  theme_minimal() + 
  labs(x = "", y = "Molecular Formula", title = "Relative metabolite abundance", fill = "relative abundance (AUC)")

plot_raw <- metabolites %>%
  filter(!is.na(Formula),
         Formula != "C14H16N2O4") %>%
  mutate(Formula = fct_relevel(Formula, Order$Formula)) %>%
  group_by(bacteria, Formula, genotype) %>%
  summarise(AUC = mean(AUC)) %>%
  ggplot(aes(x = bacteria, y = Formula)) +
  geom_tile(aes(fill = AUC)) +
  facet_grid(.~genotype) +
  scale_fill_viridis_c(oob = squish, trans = "log10", limits = c(100000, 10e6), option = "inferno") +
  theme_minimal() + 
  labs(x = "", y = "Molecular Formula", title = "Metabolite abundance",  fill = "Abundance (AUC)") 

plot_rel

```
