---
title: "Figure_3E"
author: "Mike O'Donnell"
date: "5/31/2019"
output: 
  html_document:
      code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r TA rescue}
library(rstanarm)
library(tidybayes)
library(modelr)

TAGOF <- readr::read_csv(here::here("extdata","Figure_3F.csv")) %>%
  mutate(cond = fct_relevel(cond, "Tyrosine", "Tyr+TA"),
         food =fct_relevel(food, "OP50", "JUb39"),
         TA = case_when(
           cond == "Tyrosine" ~ 0,
           cond == "Tyr+TA" ~ 4,
           cond == "Tyr+10mM_TA" ~ 10
         ),
         data_type = "raw",
         KO_data = case_when(
           date %in% c("2019_03_19",
                     "2019_04_17") & cond == "Tyrosine" ~ "repeated",
           TRUE ~ "new")) %>% droplevels()

# TAGOF <- SOS %>%
#   filter(date %in% c("2019_03_19",
#                      "2019_04_17",
#                      "2019_04_23",
#                      "2019_04_27",
#                      "2019_05_06",
#                      "2019_05_17",
#                      "2019_05_20",
#                      "2019_05_27",
#                      "2019_05_28"),
#          cond %in% c("Tyrosine", "Tyr+TA", "Tyr+10mM_TA"),
#          genotype == "N2",
#          response.time < 20) %>%
#   mutate(cond = fct_relevel(cond, "Tyrosine", "Tyr+TA"),
#          TA = case_when(
#            cond == "Tyrosine" ~ 0,
#            cond == "Tyr+TA" ~ 4,
#            cond == "Tyr+10mM_TA" ~ 10
#          ),
#          data_type = "raw",
#          group = interaction(food,cond),
#          KO_data = case_when(
#            date %in% c("2019_03_19",
#                      "2019_04_17") & cond == "Tyrosine" ~ "repeated",
#            TRUE ~ "new")) %>%
#   filter(!(food == "JUb39" & cond == "Tyr+10mM_TA")) %>% droplevels()

stan_glm <- rstanarm::stan_lmer(TAGOF, 
                      formula = log(response.time) ~ food*cond + (food | date) + (1|plateID),
                      seed = 6994,
                      cores = 4, 
                      chains = 4)

# fitted <- TAGOF %>%
#   data_grid(food,cond) %>%
#   add_fitted_draws(stan_glm, re_formula = NA) %>%
#   mutate(response.time = exp(.value), data_type = "fit")

fitted1 <- emmeans::emmeans(stan_glm, pair) %>%
  emmeans::contrast(stan_glm, "trt.vs.ctrl") %>%
  coda::as.mcmc() %>% 
  bayesplot::mcmc_intervals_data(prob = 0.66, prob_outer = 0.95) %>%
  mutate(data_type = "fit",
         food = c("JUb39", 
                  "JUb39; tdcDel::cmR",
                  "JUb39; delAADC",
                  "JUb39; tdcDel::cmR delAADC")) %>%
  mutate(food = factor(food, levels = c("OP50", 
                                        "JUb39",
                                        "JUb39; tdcDel::cmR",
                                        "JUb39; delAADC",
                                        "JUb39; tdcDel::cmR delAADC"))) 

plot <- TAGOF %>%
  format_SOS(., day_correct = genotype) %>%
  ggplot(aes(x = data_type)) +
  geom_relLatency(
    fitted = fitted1,
    fillvar = food,
    dotvar = food,
    yvar = rel_log
  ) +
  facet_grid(.~food + cond)

 plot <- TAGOF %>%
 mutate(response.time = case_when(
    response.time < 1 ~ 1, 
    TRUE ~ response.time
  ))  %>%
  ggplot(aes(x = data_type, y = response.time)) +
  stat_summary(geom = "bar", fun.y = mean, aes(fill = food), width = 0.6, alpha = 0.5) +
  ggbeeswarm::geom_quasirandom(aes(colour = food, pch = KO_data), width = 0.2, alpha = 0.75) +
  facet_grid(.~food + cond, 
             labeller = labeller(genotype = label_wrap_gen(10), 
                                 food = as_labeller(c("OP50" = "",
                                                    "JUb39" = "")))) +
   scale_color_plot(palette = "grey-blue-light", drop = TRUE) +
   scale_fill_plot(palette = "grey-blue-light", drop = TRUE) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
  add.n('data_type', y.pos = 0.9) +
  stat_pointinterval(aes(y=response.time, x = 1.5),
                     data = fitted, fatten_point = 0,
                     size_range = c(0.3, 1), colour = "darkgrey") +
  stat_summary(data = fitted,
               aes(y=response.time, x = 1.5),
               fun.y = median,
               fun.ymin = median,
               fun.ymax = median,
               geom = "crossbar",
               width = 0.05,
               lwd = 0.35,
               colour = "darkgrey") +
  labs(x = "genotype",
       y = "time to reversal (s)") +
  guides(colour = FALSE, fill = FALSE) +
  theme(axis.text.x = element_blank()) +
  scale_y_log10()

 #singular fit
  TAGOF %>% lme4::lmer(data = ., log(response.time) ~ food*cond + (1|plateID) + (food|date))
  #non-singular fit
  TAGOF %>% lme4::lmer(data = ., log(response.time) ~ food*cond + (food|date)) %>% 
  emmeans(~ cond | food) %>% contrast(method = "pairwise")
  
```

