---
title: "Figure_2B - move to "
author: "Mike O'Donnell"
date: "6/19/2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)

```

```{r dataload}
library(tidyverse)
library(patchwork)

filepath <- here::here("extdata/Figure_2B.csv")

GPCR_data <- read.csv(filepath) %>%
  dplyr::filter(strain %in% c("OP50", "JUb39"), genotype != "tbh-1") %>% droplevels() %>%
  format_AvoidData(day.correct = "genotype") %>%
  mutate(plate = factor(seq(1:nrow(.))),
         genotype = factor(genotype, levels = c("N2","ser-3","octr-1","tyra-3","tyra-2","ser-1","dop_quad")))

plot = GPCR_data %>%
  plot_plasticityIndex(xvar = strain) + labs(title = "day corrected") +
  scale_color_plot(palette = "grey-blue", drop = TRUE) + guides(color = FALSE) + 
  facet_grid(.~genotype)

plot + coord_cartesian(ylim = c(-3,4))

glmm <- lme4::glmer(data = GPCR_data, 
                    formula = cbind(nCue,nControl) ~ genotype * strain + (1 | date) +  (1|plate),
                    family = binomial)

stan_glmm <-  rstanarm::stan_glmer(data = GPCR_data, 
                  formula = cbind(nCue,nControl) ~ 
                    genotype * strain + (1 + strain + genotype | date) +  (1|plate),
                  chains = 6, cores = 4, seed = 2000,iter=6000,
                  family = binomial,
    control = list(adapt_delta=0.99))

emmeans::ref_grid(stan_glmm) %>% emmeans::contrast(., method = "revpairwise", by = "genotype") %>% str()#%>% broom::tidy() 

#emmeans::ref_grid(stan_glmm) %>% emmeans::emmeans(., pairwise ~ strain | genotype)


lsm.list <- emmeans::ref_grid(glmm) %>% emmeans::lsmeans(., pairwise ~ strain | genotype) #%>% summary(adjust = "bon")
contrasts <- update(lsm.list$contrast, adjust = "mvt", by.vars = NULL)


sciplot::bargraph.CI(data = GPCR_data,
                     x.factor = genotype,
                     response = rel.Logit,
                     group = strain,
                     ylim = c(-0.75,3),
                     #ylim = c(-1,0.5),
                     col=rep(c("#827E7E","#484CC7"), 7),
                     space = (rep(c(0.2, 0.05), 7))
                     )

```
