---
title: "Figure_3E"
author: "Mike O'Donnell"
date: "5/30/2019"
output: 
  html_document:
      code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r Ps tdcKO}
library(tidyverse)
library(emmeans)
library(modelr)
library(tidybayes)
library(kableExtra)

# SOS <- readr::read_csv(here::here("extdata","SOS_OP50_JUb39.csv")) %>%
#   mutate(food = factor(food, levels = c("OP50",
#                                         "JUb39",
#                                         "BL21",
#                                         "BL21_tdcGOF",
#                                         "BL21_tdcK>A",
#                                         "655",
#                                         "655-tdcDel",
#                                         "JUb39; tdcDel::cmR",
#                                         "JUb39; tdcopDel",
#                                         "JUb39; tdcDel::cmR delAADC",
#                                         "JUb39; delAADC")),
#          genotype = factor(genotype, levels = c("N2",
#                                                 "tbh-1",
#                                                 "tdc-1",
#                                                 "octr-1",
#                                                 "ser-3",
#                                                 "tyra-2",
#                                                 "tyra-2; ex[sra6p::tyra-2]",
#                                                 "tyra-2; octr-1",
#                                                 "octr-1; ex[sra6p::octr-1]",
#                                                 "tdc-1; tyra-2",
#                                                 "tdc-1; tbh-1")),
#          paralyzed = case_when(response.time == 20 ~ "paralyzed",
#                                TRUE ~ "non-paralyzed")) %>%
#   #group_by(date, genotype, food, cond, cue) %>%
#   #tidyr::nest() %>%
#   mutate(plateID = interaction(genotype, food, date, cue, cond)) #%>% tidyr::unnest()
# 
# SOSKO <-  SOS %>% dplyr::filter(cond == "Tyrosine",
#                                 cue == "oct_1.0",
#                       genotype %in% c("N2"),
#                       food %in% c("OP50", "JUb39", "JUb39; tdcDel::cmR", "JUb39; tdcDel::cmR delAADC", "JUb39; delAADC"),
#                       response.time < 20,
#                       #date %in% c("2019_02_13","2019_02_15"),
#                       date %in% c("2019_01_07", #need to subset days
#                                   "2019_01_14",
#                                   "2018_10_23",
#                                   "2018_10_29",
#                                   "2018_11_13",
#                                   "2019_02_13",
#                                   "2019_02_15",
#                                   "2019_03_06",
#                                   "2019_03_19",
#                                   '2019_04_17',
#                                   '2019_04_23',
#                                   '2019_04_27',
#                                   '2019_04_29')) %>%
#   mutate(food = fct_relevel(food, c("OP50", "JUb39", "JUb39; tdcDel::cmR", "JUb39; delAADC")),
#                             data_type = "raw") %>%
#   droplevels() %>%
#   mutate(log.response = log(response.time))

filepath <- here::here("extdata/Figure_3d_SOSJUKO.csv")

SOSKO <- read_csv(filepath) %>%
  mutate(SOSKO, food = fct_relevel(food, c("OP50", "JUb39", "JUb39; tdcDel::cmR", "JUb39; delAADC")))
         
         
lmer <- SOSKO %>%
    lme4::lmer(., formula = log10(response.time) ~ food  + (1|date) + (1|plateID))

library(rstanarm)

stan_glm <- SOSKO %>%
  rstanarm::stan_lmer(., 
                      formula = log(response.time) ~ food + (1 | date) + (1|plateID),
                      cores = 4, 
                      chains = 4,
                      seed = 637,
                      adapt_delta = 0.99)


# get Bayesian cred intervals for differences between food
fitted1 <- emmeans::ref_grid(stan_glm) %>%
  emmeans::contrast("trt.vs.ctrl") %>%
  coda::as.mcmc() %>% 
  bayesplot::mcmc_intervals_data(prob = 0.66, prob_outer = 0.95) %>%
  mutate(data_type = "fit",
         food = c("JUb39", 
                  "JUb39; tdcDel::cmR",
                  "JUb39; delAADC",
                  "JUb39; tdcDel::cmR delAADC")) %>%
  mutate(food = factor(food, levels = c("OP50", 
                                        "JUb39",
                                        "JUb39; tdcDel::cmR",
                                        "JUb39; delAADC",
                                        "JUb39; tdcDel::cmR delAADC"))) #%>% 
  #mutate_if(is.numeric, function(.) {. * -1})

plot <- format_SOS(SOSKO, day_correct = genotype) %>%
  ggplot(aes(x = data_type)) +
  geom_relLatency(fitted = fitted1,
                  fillvar = food,
                  dotvar = food,
                  yvar = rel_log) +
  scale_color_plot("grey-blue-light", drop = TRUE) +
  scale_fill_plot("grey-blue-light", drop = TRUE) +
  facet_grid(.~genotype+food) +
  add.n('data_type', y.pos = -1.6) +
  labs(x = "genotype",
       y = "relative reversal latency [log(s)]") +
  guides(colour = FALSE, fill = FALSE) +
  coord_cartesian(ylim = c(-1.7,2)) +
  theme(axis.text.x = element_blank())

## for plotting non-relative bargraphs
# fitted <- SOSKO %>%
#   data_grid(food) %>%
#   add_fitted_draws(stan_glm, re_formula = NA) %>%
#   mutate(response.time = exp(.value), data_type = "fit")

# plot <- SOSKO %>%
# mutate(response.time = case_when(
#     response.time < 1 ~ 1, 
#     TRUE ~ response.time
#   ),
#   food = fct_relevel(food, "OP50")) %>%
#   ggplot(aes(x = data_type, y = response.time)) +
#   stat_summary(geom = "bar", fun.y = mean, aes(fill = food), width = 0.6, alpha = 0.5) +
#   ggbeeswarm::geom_quasirandom(aes(colour = food), width = 0.2, alpha = 0.75) +
#   scale_color_plot("grey-blue-light", drop = TRUE) +
#   scale_fill_plot("grey-blue-light", drop = TRUE) +
#   facet_grid(.~genotype + food, 
#              labeller = labeller(genotype = label_wrap_gen(10), 
#                                  food = as_labeller(c("OP50" = "",
#                                                     "JUb39" = "")))) +
#   stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
#   add.n('data_type', y.pos = 0.9) +
#   stat_pointinterval(aes(y=response.time, x = 1.4),
#                      data = fitted, fatten_point = 0,
#                      size_range = c(0.3, 1), colour = "darkgrey") +
#   stat_summary(data = fitted,
#                aes(y=response.time, x = 1.4),
#                fun.y = median,
#                fun.ymin = median,
#                fun.ymax = median,
#                geom = "crossbar",
#                width = 0.05,
#                lwd = 0.35,
#                colour = "darkgrey") +
#   labs(x = "genotype",
#        y = "time to reversal (s)") +
#   guides(colour = FALSE, fill = FALSE) +
#   theme(axis.text.x = element_blank()) +
#   scale_y_log10()

plot


lmer %>%
  emmeans::ref_grid() %>%
  emmeans::contrast(method = "pairwise", type = "response") %>%
  broom::tidy() %>% 
  mutate_if(is.numeric, ~ round(., 3)) %>% kable() %>% kable_styling(bootstrap_options = c("striped", "hover"))


```

