---
title: "Figure_2d_TA_succinate_"
author: Michael P. O’Donnell^[1,3], Bennett Fox^[2],Pin-Hao Chao^[1], Frank Schroeder^[2],
  and Piali Sengupta^[1,3]
date: "8/2/2019"
output: 
  html_document:
    code_folding: hide
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
library(tidyverse)
library(patchwork)
library(tidybayes)
library(modelr)
library(emmeans)
library(magrittr)
library(emmeans)
library(rstanarm)
theme_set(theme_my)
```

```{r data load}
library(scales)

TAsucc <- read_csv('extdata/Figure_2B_3G_TAsucc.csv') %>%
  filter(food %in% c("OP50", "JUb39")) %>%
  mutate(food = fct_relevel(food, c("OP50", "JUb39")))

plot <- TAsucc %>%
  ggplot(aes(x = food, y = AUC)) +
  #geom_point(aes(colour = food)) +
  geom_bardots(fillvar = food, dotvar = food) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
  scale_color_plot("grey-blue", drop = TRUE) +
  scale_fill_plot("grey-blue", drop = TRUE) +
  add.n('food', y.pos = 0.5) +
  labs(x = "food",
       y = "AUC") +
  guides(colour = FALSE) +
  theme(axis.text.x = element_blank()) +
  facet_grid(.~genotype) +
  scale_y_continuous(trans = 'log10',
                        breaks = trans_breaks('log10', function(x) 10^x),
                        labels = trans_format('log10', math_format(10^.x)))


lin_mod <- lm(TAsucc, formula = AUC ~ genotype * food)
lin_mod %>% emmeans::ref_grid() %>% emmeans::contrast(method = "pairwise")

plot

```

