---
title: "Figure_2D"
author: "Mike O'Donnell"
date: "6/5/2019"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r 30pct data}
library(tidyverse)
library(emmeans)
library(modelr)
library(tidybayes)
library(kableExtra)
library(patchwork)
theme_set(theme_my)


SOS_30pct <- read_csv(here::here('extdata/Figure_2D.csv')) %>%
  mutate(food = fct_relevel(food, "OP50"),
         genotype = fct_relevel(genotype, "N2"),
         data_type = "raw")


SOS_30pct %>% ggplot(aes(x = genotype, y = response.time)) +
  ggbeeswarm::geom_quasirandom(aes(colour = food), width = 0.2) +
  scale_color_plot("grey-blue", drop = TRUE) +
  facet_grid(.~food) +
  add.mean('response.time', colour = "red") +
  add.quartiles('response.time') +
  theme_my +
  labs(x = "food",
       y = "time to reversal (s)")

stan_mod <- rstanarm::stan_glmer(data = SOS_30pct, log(response.time) ~ food * genotype + (1|date) + (1|plateID),
                       family = gaussian,
                       seed = 694,
                       chains = 6,
                       cores = 6)


fitted1 <-  emmeans::ref_grid(stan_mod) %>%
  emmeans::contrast("trt.vs.ctrl") %>%
  coda::as.mcmc() %>% 
  bayesplot::mcmc_intervals_data(prob = 0.66, prob_outer = 0.95) %>%
  mutate(genotype = factor(c("N2", "tdc-1", "tdc-1")),
         food = factor(c("JUb39", "OP50", "JUb39")))



```

```{r frequentist stats}
sjstats::equi_test(stan_mod)

# frequentist glmm (log transformed)
lmer <- lme4::lmer(data = SOS_30pct, log(response.time) ~ food * genotype + (1|date) + (1|plateID))

lmer %>% emmeans(pairwise ~ food | genotype)
  lmer %>% emmeans(pairwise ~ genotype | food)

#### plot all relative to N2 OP50 control####
 SOS_normalized <- SOS_30pct %>% 
    #normalize to N2, OP50
    mutate(response.time = case_when(
        response.time < 1 ~ 1,
        TRUE ~ response.time)) %>%
      group_by(genotype, food, date) %>%
      summarise(meanOP = mean(log(response.time))) %>%
      filter(food == "OP50", genotype == "N2") %>%
      ungroup() %>%
      select(date, meanOP) %>%
      full_join(., SOS_30pct) %>%
      mutate(rel_log = log(response.time) - meanOP,
             food = fct_relevel(food, "OP50")) 
    ## plot ##
plot <- SOS_normalized %>% ggplot(aes(x = data_type)) +
  geom_relLatency(
    fitted = fitted1,
    fillvar = food,
    dotvar = food,
    yvar = rel_log
  ) +
  scale_color_plot("grey-blue", drop = TRUE) +
  scale_fill_plot("grey-blue", drop = TRUE) +
  facet_grid(. ~ food + genotype) +
  add.n("data_type", y.pos = -1.9) +
  labs(
    x = "genotype",
    y = "relative reversal latency [log(s)]"
  ) +
  guides(colour = FALSE) +
  coord_cartesian(ylim = c(-2,2)) +
  theme(axis.text.x = element_blank())
  
  
# plot bars
#    plot <- SOS_30pct %>%
#   mutate(response.time = case_when(
#     response.time < 1 ~ 1, 
#     TRUE ~ response.time
#   ),
#   food = fct_relevel(food, "OP50")) %>%
#   ggplot(aes(x = data_type, y = response.time)) +
#   stat_summary(geom = "bar", fun.y = mean, aes(fill = food), width = 0.5, alpha = 0.5) +
#   ggbeeswarm::geom_quasirandom(aes(colour = food), width = 0.2, alpha = 0.75) +
#   scale_color_plot("grey-blue", drop = TRUE) +
#   scale_fill_plot("grey-blue", drop = TRUE) +
#   facet_grid(.~food + genotype, 
#              labeller = labeller(genotype = label_wrap_gen(10), 
#                                  food = as_labeller(c("OP50" = "",
#                                                     "JUb39" = "")))) +
#   stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
#   add.n('data_type', y.pos = 0.9) +
#   stat_pointinterval(aes(y=response.time, x = 1.3),
#                      data = fitted, fatten_point = 0,
#                      size_range = c(0.3, 1), colour = "grey") +
#   stat_summary(data = fitted,
#                aes(y=response.time, x = 1.3),
#                fun.y = median,
#                fun.ymin = median,
#                fun.ymax = median,
#                geom = "crossbar",
#                width = 0.05,
#                lwd = 0.35,
#                colour = "grey") +
#   labs(x = "genotype",
#        y = "time to reversal (s)") +
#   guides(colour = FALSE) +
#   theme(axis.text.x = element_blank()) +
#   scale_y_log10() +
#   guides(fill = FALSE)
#   coord_cartesian(ylim = c(0,16))

gt <- ggplot_gtable(ggplot_build(plot))
gt$widths[c(8,12)] = 5*gt$widths[c(8,12)]
gt$widths[c(6,10,14)] = .3*gt$widths[c(6,10,14)]
grid::grid.draw(gt)


# F-test for interaction term :
car::Anova(lmer, test = "F")


# comaprison of mcmc intervals for supplement:
mcmc.comps <- emmeans(stan_mod, ~ food | genotype, type = "response") %>%
  contrast(method = "pairwise") %>%
  coda::as.mcmc() #%>%
p1 <- bayesplot::mcmc_areas(mcmc.comps)
p2 <- bayesplot::mcmc_intervals(mcmc.comps,prob = 0.66, prob_outer = 0.95)

p1 + p2 + theme(axis.text.y = element_blank())
```
