---
title: "Figure_4D"
author: "Mike O'Donnell"
date: "6/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r dataload}
library(tidyverse)
library(patchwork)

filepath <- here::here("extdata/Figure_4D.csv")

tdcGOF <- read.csv(filepath) %>% 
  format_AvoidData(day.correct = "genotype") %>%
  #filter(genotype == "N2") %>%
  mutate(strain = factor(strain, levels = c("OP50", "JUb39", "BL21", "BL21_tdc+", 'E.d.655', 'E.d.655_tdcDel', "JUb39; tdcDel::cmR")),
         plate = factor(seq(1:nrow(.))))

p1 <- tdcGOF %>% 
  plot_plasticityIndex(xvar = strain) +
    scale_color_plot('multi-control', drop = TRUE) +
  guides(color = FALSE) + labs(title = "1-oct") +
  theme_my_ppt + facet_grid(.~genotype)

p2 = tdcGOF %>% 
  plot_ChemoIndex(xvar = strain, plot.pos = FALSE) +
  scale_color_plot('multi-control', drop = TRUE) +
  guides(fill = FALSE) + labs(title = "1-oct") +
  theme_my_ppt + facet_grid(.~genotype)

p1 + p2

# 1 day data
glmm <- lme4::glmer(data = tdcGOF, 
                    formula = cbind(nCue,nControl) ~ strain + (1|plate),
                    family = binomial,
                    control= lme4::glmerControl(optimizer="bobyqa"))

lsm.list <- lsmeans::ref.grid(glmm) %>% lsmeans::lsmeans(., pairwise ~ strain ) #%>% summary(adjust = "bon")
contrasts <- update(lsm.list$contrast, adjust = "mvt", by.vars = NULL)

sciplot::bargraph.CI(data = tdcGOF,
                     x.factor = strain,
                     response = rel.Logit,
                     #group = strain,
                     #ylim = c(-.5,3),
                     ylim = c(-.5,3),
                     col=c("#827E7E","#484CC7","#E6DDDD","#A3A3FA"),
                     err.width = 0.05
                     )
```
