---
title: "Figure_4B_octr-1TA"
author: "Mike O'Donnell"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ProvidenciaChemo)
```

```{r TA rescue}
library(rstanarm)
library(tidybayes)
library(modelr)

#readr::read_csv(here::here("extdata","Figure_3E.csv")) %>%

TAGOF <- SOS %>% 
  filter(genotype %in% c("N2", "octr-1"),
         cond %in% c("Tyrosine", "Tyr+10mM_TA"),
         food == "JUb39; tdcDel::cmR delAADC",
         date %in% c("2019_05_28", "2019_06_03"),
         response.time < 20) %>%
  mutate(cond = fct_relevel(cond, "Tyrosine"),
         food =fct_relevel(food, "OP50", "JUb39"),
         TA = case_when(
           cond == "Tyrosine" ~ 0,
           cond == "Tyr+10mM_TA" ~ 10
         ),
         data_type = "raw") %>% droplevels()

stan_glm <- rstanarm::stan_lmer(TAGOF, 
                      formula = log(response.time) ~ genotype*cond + (cond | date) + (1|plateID),
                      #formula = log(response.time) ~ genotype*cond + (1|plateID),
                      seed = 6994,
                      cores = 4, 
                      chains = 4,
                      adapt_delta = 0.999)

fitted <- TAGOF %>%
  data_grid(genotype,cond, date = "2019_05_28", .model = stan_glm) %>%
  add_fitted_draws(stan_glm, all_new_levels = TRUE) %>%
  mutate(response.time = exp(.value), data_type = "fit")

 plot <- TAGOF %>%
 mutate(response.time = case_when(
    response.time < 1 ~ 1, 
    TRUE ~ response.time
  ))  %>%
  ggplot(aes(x = data_type, y = response.time)) +
  stat_summary(geom = "bar", fun.y = mean, fill = "#2F8A34", width = 0.6, alpha = 0.5) +
  ggbeeswarm::geom_quasirandom(colour = "#2F8A34", width = 0.2, alpha = 0.75) +
  facet_grid(.~genotype + cond, 
             labeller = labeller(genotype = label_wrap_gen(10), 
                                 food = as_labeller(c("OP50" = "",
                                                    "JUb39" = "")))) +
   scale_color_plot(palette = "grey-blue-light", drop = TRUE) +
   scale_fill_plot(palette = "grey-blue-light", drop = TRUE) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.2) +
  add.n('data_type', y.pos = 0.9) +
  stat_pointinterval(aes(y=response.time, x = 1.5),
                     data = fitted, fatten_point = 0,
                     size_range = c(0.3, 1), colour = "darkgrey") +
  stat_summary(data = fitted,
               aes(y=response.time, x = 1.5),
               fun.y = median,
               fun.ymin = median,
               fun.ymax = median,
               geom = "crossbar",
               width = 0.05,
               lwd = 0.35,
               colour = "darkgrey") +
  labs(x = "genotype",
       y = "time to reversal (s)") +
  guides(colour = FALSE, fill = FALSE) +
  theme(axis.text.x = element_blank()) +
  scale_y_log10()

 #singular fit
  TAGOF %>% lme4::lmer(data = ., log(response.time) ~ genotype*cond + (1|plateID) + (1|date)) %>% summary()
  #singular fit 
  TAGOF %>% lme4::lmer(data = ., log(response.time) ~ genotype*cond + (cond|date)) #%>% 
  #singular fit 
  TAGOF %>% lme4::lmer(data = ., log(response.time) ~ genotype*cond + (1|plateID)) %>% summary()
  
  glm_mod <- TAGOF %>% lm(data = ., log(response.time) ~ genotype*cond) 
  glm_mod %>% ref_grid() %>% contrast(method = "pairwise")

```
